# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\python project\VS\UI\basicUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1261, 887)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.PtInputTableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.PtInputTableWidget.setGeometry(QtCore.QRect(740, 50, 431, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PtInputTableWidget.sizePolicy().hasHeightForWidth())
        self.PtInputTableWidget.setSizePolicy(sizePolicy)
        self.PtInputTableWidget.setMinimumSize(QtCore.QSize(0, 60))
        self.PtInputTableWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.PtInputTableWidget.setObjectName("PtInputTableWidget")
        self.PtInputTableWidget.setColumnCount(0)
        self.PtInputTableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(750, 130, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(950, 20, 54, 12))
        self.label_2.setObjectName("label_2")
        self.PtSetNumber = QtWidgets.QLCDNumber(self.centralWidget)
        self.PtSetNumber.setGeometry(QtCore.QRect(1030, 10, 64, 23))
        self.PtSetNumber.setObjectName("PtSetNumber")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(690, 10, 20, 841))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.PtShowWidget = MatplotlibWidget(self.centralWidget)
        self.PtShowWidget.setGeometry(QtCore.QRect(22, 12, 661, 821))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PtShowWidget.sizePolicy().hasHeightForWidth())
        self.PtShowWidget.setSizePolicy(sizePolicy)
        self.PtShowWidget.setMinimumSize(QtCore.QSize(600, 400))
        self.PtShowWidget.setObjectName("PtShowWidget")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(739, 300, 481, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.PtSetListView = QtWidgets.QListView(self.centralWidget)
        self.PtSetListView.setGeometry(QtCore.QRect(740, 150, 141, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PtSetListView.sizePolicy().hasHeightForWidth())
        self.PtSetListView.setSizePolicy(sizePolicy)
        self.PtSetListView.setObjectName("PtSetListView")
        self.VectorShowCheckBox = QtWidgets.QCheckBox(self.centralWidget)
        self.VectorShowCheckBox.setGeometry(QtCore.QRect(900, 240, 107, 16))
        self.VectorShowCheckBox.setObjectName("VectorShowCheckBox")
        self.CoordinateRadioButton = QtWidgets.QRadioButton(self.centralWidget)
        self.CoordinateRadioButton.setGeometry(QtCore.QRect(1080, 660, 65, 16))
        self.CoordinateRadioButton.setObjectName("CoordinateRadioButton")
        self.PtAddButton = QtWidgets.QPushButton(self.centralWidget)
        self.PtAddButton.setGeometry(QtCore.QRect(900, 150, 75, 23))
        self.PtAddButton.setObjectName("PtAddButton")
        self.PtDelButton = QtWidgets.QPushButton(self.centralWidget)
        self.PtDelButton.setGeometry(QtCore.QRect(900, 200, 75, 23))
        self.PtDelButton.setObjectName("PtDelButton")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(1010, 120, 101, 16))
        self.label_3.setObjectName("label_3")
        self.CSAddButton = QtWidgets.QPushButton(self.centralWidget)
        self.CSAddButton.setGeometry(QtCore.QRect(1070, 720, 75, 23))
        self.CSAddButton.setObjectName("CSAddButton")
        self.TFMatrixtableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.TFMatrixtableWidget.setGeometry(QtCore.QRect(730, 640, 311, 192))
        self.TFMatrixtableWidget.setObjectName("TFMatrixtableWidget")
        self.TFMatrixtableWidget.setColumnCount(0)
        self.TFMatrixtableWidget.setRowCount(0)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(740, 610, 54, 12))
        self.label_4.setObjectName("label_4")
        self.CStreeWidget = QtWidgets.QTreeWidget(self.centralWidget)
        self.CStreeWidget.setGeometry(QtCore.QRect(1010, 150, 161, 141))
        self.CStreeWidget.setObjectName("CStreeWidget")
        self.CStreeWidget.headerItem().setText(0, "1")
        self.CSDelButton = QtWidgets.QPushButton(self.centralWidget)
        self.CSDelButton.setGeometry(QtCore.QRect(1070, 760, 75, 23))
        self.CSDelButton.setObjectName("CSDelButton")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(750, 20, 101, 16))
        self.label_5.setObjectName("label_5")
        self.CSEulerTableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.CSEulerTableWidget.setGeometry(QtCore.QRect(740, 340, 431, 61))
        self.CSEulerTableWidget.setObjectName("CSEulerTableWidget")
        self.CSEulerTableWidget.setColumnCount(0)
        self.CSEulerTableWidget.setRowCount(0)
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(750, 320, 54, 12))
        self.label_6.setObjectName("label_6")
        self.CSTRTableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.CSTRTableWidget.setGeometry(QtCore.QRect(740, 460, 431, 61))
        self.CSTRTableWidget.setObjectName("CSTRTableWidget")
        self.CSTRTableWidget.setColumnCount(0)
        self.CSTRTableWidget.setRowCount(0)
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(750, 430, 54, 12))
        self.label_7.setObjectName("label_7")
        self.AnimationButton = QtWidgets.QPushButton(self.centralWidget)
        self.AnimationButton.setGeometry(QtCore.QRect(1060, 590, 121, 23))
        self.AnimationButton.setObjectName("AnimationButton")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "点集内容"))
        self.label_2.setText(_translate("MainWindow", "点数"))
        self.VectorShowCheckBox.setText(_translate("MainWindow", "Show Pt Vector"))
        self.CoordinateRadioButton.setText(_translate("MainWindow", "show CS"))
        self.PtAddButton.setText(_translate("MainWindow", "Pt Add"))
        self.PtDelButton.setText(_translate("MainWindow", "Pt Del"))
        self.label_3.setText(_translate("MainWindow", "坐标系及点集"))
        self.CSAddButton.setText(_translate("MainWindow", "CS Add"))
        self.label_4.setText(_translate("MainWindow", "转换矩阵"))
        self.CSDelButton.setText(_translate("MainWindow", "CS Del"))
        self.label_5.setText(_translate("MainWindow", "单点坐标"))
        self.label_6.setText(_translate("MainWindow", "Euler角"))
        self.label_7.setText(_translate("MainWindow", "平移"))
        self.AnimationButton.setText(_translate("MainWindow", "Animation Start"))

from UI.MatplotlibWidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

